// Regenerates lib/src/budoux/model_*.dart from the upstream BudouX models.
//
//   dart run tool/generate_models.dart            # default tag below
//   dart run tool/generate_models.dart v0.9.2
//   dart run tool/generate_models.dart --dir ~/src/budoux/budoux/models
//
// The models are Copyright 2021 Google LLC, Apache License 2.0
// (third_party/budoux/LICENSE). Each generated file keeps that notice.
import 'dart:convert';
import 'dart:io';

const defaultTag = 'v0.9.2';

const models = {
  'ja': 'budouxJa',
  'zh-hans': 'budouxZhHans',
  'zh-hant': 'budouxZhHant',
};

Future<void> main(List<String> args) async {
  String? dir;
  var tag = defaultTag;
  for (var i = 0; i < args.length; i++) {
    if (args[i] == '--dir') {
      dir = args[++i];
    } else {
      tag = args[i];
    }
  }
  final client = HttpClient();
  try {
    for (final entry in models.entries) {
      final name = entry.key;
      final String json;
      final String source;
      if (dir != null) {
        json = File('$dir/$name.json').readAsStringSync();
        source = '$dir/$name.json';
      } else {
        source = 'https://raw.githubusercontent.com/google/budoux/$tag/budoux/models/$name.json';
        final req = await client.getUrl(Uri.parse(source));
        final res = await req.close();
        if (res.statusCode != 200) {
          throw HttpException('HTTP ${res.statusCode} for $source');
        }
        json = await res.transform(utf8.decoder).join();
      }
      final model = (jsonDecode(json) as Map<String, dynamic>).map(
        (k, v) => MapEntry(k, (v as Map<String, dynamic>).map((f, s) => MapEntry(f, s as int))),
      );
      final out = File('lib/src/budoux/model_${name.replaceAll('-', '_')}.dart');
      out.writeAsStringSync(_emit(model, entry.value, name, tag, source));
      final features = model.values.fold<int>(0, (a, g) => a + g.length);
      stdout.writeln('${out.path}: ${model.length} groups, $features features');
    }
  } finally {
    client.close();
  }
}

String _emit(Map<String, Map<String, int>> model, String ident, String name, String tag, String source) {
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/generate_models.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// BudouX $name model, google/budoux $tag (budoux/models/$name.json).')
    ..writeln('// Source: $source')
    ..writeln('//')
    ..writeln('// Copyright 2021 Google LLC')
    ..writeln('//')
    ..writeln('// Licensed under the Apache License, Version 2.0 (the "License");')
    ..writeln('// you may not use this file except in compliance with the License.')
    ..writeln('// You may obtain a copy of the License at')
    ..writeln('//')
    ..writeln('//     https://www.apache.org/licenses/LICENSE-2.0')
    ..writeln('//')
    ..writeln('// Unless required by applicable law or agreed to in writing, software')
    ..writeln('// distributed under the License is distributed on an "AS IS" BASIS,')
    ..writeln('// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.')
    ..writeln('// See the License for the specific language governing permissions and')
    ..writeln('// limitations under the License.')
    ..writeln()
    ..writeln('/// The BudouX `$name` model: feature group → feature → score.')
    ..writeln('const Map<String, Map<String, int>> $ident = {');
  // Keep upstream order (it is the order of the JSON file).
  for (final g in model.entries) {
    b.writeln("  '${g.key}': {");
    final items = g.value.entries.map((e) => '${_lit(e.key)}: ${e.value}').toList();
    // A few features per line keeps the file compact but diffable.
    for (var i = 0; i < items.length; i += 8) {
      b.writeln('    ${items.sublist(i, i + 8 > items.length ? items.length : i + 8).join(', ')},');
    }
    b.writeln('  },');
  }
  b.writeln('};');
  return b.toString();
}

String _lit(String s) {
  final b = StringBuffer("'");
  for (final r in s.runes) {
    switch (r) {
      case 0x27: // '
        b.write(r"\'");
      case 0x5C: // \
        b.write(r'\\');
      case 0x24: // $
        b.write(r'\$');
      default:
        if (r < 0x20 || r == 0x7F || (r >= 0x2028 && r <= 0x2029) || (r >= 0xD800 && r <= 0xDFFF)) {
          b.write('\\u{${r.toRadixString(16)}}');
        } else {
          b.writeCharCode(r);
        }
    }
  }
  b.write("'");
  return b.toString();
}
